const noncePattern = /^[A-Za-z0-9+/=]+$/;

/**
 * Builds the document policy used by Proxy. The nonce is generated by the server for each
 * request, never accepted from a browser header or query parameter.
 */
export function createContentSecurityPolicy(nonce: string): string {
  if (!noncePattern.test(nonce)) throw new Error('INVALID_CSP_NONCE');
  return [
    "default-src 'self'",
    "base-uri 'self'",
    "frame-ancestors 'none'",
    "form-action 'self'",
    "img-src 'self' data: blob: https:",
    "object-src 'none'",
    "media-src 'self' blob:",
    "font-src 'self' data:",
    "manifest-src 'self'",
    "worker-src 'self' blob:",
    `script-src 'self' 'nonce-${nonce}' 'strict-dynamic' https://static.cloudflareinsights.com`,
    "style-src 'self' 'unsafe-inline'",
    "connect-src 'self' https://cloudflareinsights.com",
  ].join('; ');
}
